apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook-receiver-frontend
spec:
  port:
    targetPort: 8080
  to:
    name: el-webhook-receiver-frontend
    kind: Service
    weight: 100
