apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook-receiver-frontend
spec:
  serviceAccountName: webhook-receiver
  triggers:
    - template:
        name: webhook-receiver-frontend
      bindings:
        - ref: webhook-receiver-frontend
