apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: webhook-receiver-frontend
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: team2-final-frontend
    spec:
      params:
      - name: app-name
        value: "team2-final-frontend"
      - name: source-repo
        value: "https://github.com/jm-carnicero/bootcamp_frontend"
      - name: image-repo
        value: "quay.io/mhillb/team2-final-frontend"
      pipelineRef:
        name: team2-final-frontend
      serviceAccountName: build-robot
      workspaces:
      - name: pipeline-shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce 
            resources:
              requests:
                storage: 1Gi
      - name: manifest-target-repo
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce 
            resources:
              requests:
                storage: 1Gi
      - name: git-credentials-frontend
        secret:
          secretName: git-credentials-frontend

